{"timestamp": "2024-11-18T14:45:17.408317", "level": "ERROR", "name": "error_logger", "module": "logger", "funcName": "handle_exception", "message": "Uncaught exception", "exc_info": "Traceback (most recent call last):\n  File \"/home/abin/Documents/GitHub/eeg-mlflow/eeg_analysis/run_pipeline.py\", line 11, in <module>\n    from src.processing.data_loader import load_eeg_data\nImportError: cannot import name 'load_eeg_data' from 'src.processing.data_loader' (/home/abin/Documents/GitHub/eeg-mlflow/eeg_analysis/src/processing/data_loader.py)", "function": "handle_exception", "line": 125}
{"timestamp": "2024-11-18T14:49:24.584664", "level": "ERROR", "name": "error_logger", "module": "logger", "funcName": "handle_exception", "message": "Uncaught exception", "exc_info": "Traceback (most recent call last):\n  File \"/home/abin/Documents/GitHub/eeg-mlflow/eeg_analysis/run_pipeline.py\", line 18, in <module>\n    from src.models.patient_trainer import PatientLevelTrainer\n  File \"/home/abin/Documents/GitHub/eeg-mlflow/eeg_analysis/src/models/__init__.py\", line 1, in <module>\n    from .patient_trainer import train_patient_model\n  File \"/home/abin/Documents/GitHub/eeg-mlflow/eeg_analysis/src/models/patient_trainer.py\", line 3, in <module>\n    from src.models.base_trainer import BaseTrainer\nImportError: cannot import name 'BaseTrainer' from 'src.models.base_trainer' (/home/abin/Documents/GitHub/eeg-mlflow/eeg_analysis/src/models/base_trainer.py)", "function": "handle_exception", "line": 125}
{"timestamp": "2024-11-18T14:51:36.205160", "level": "ERROR", "name": "error_logger", "module": "logger", "funcName": "handle_exception", "message": "Uncaught exception", "exc_info": "Traceback (most recent call last):\n  File \"/home/abin/Documents/GitHub/eeg-mlflow/eeg_analysis/run_pipeline.py\", line 18, in <module>\n    from src.models.patient_trainer import PatientLevelTrainer\n  File \"/home/abin/Documents/GitHub/eeg-mlflow/eeg_analysis/src/models/__init__.py\", line 1, in <module>\n    from .patient_trainer import train_patient_model\nImportError: cannot import name 'train_patient_model' from 'src.models.patient_trainer' (/home/abin/Documents/GitHub/eeg-mlflow/eeg_analysis/src/models/patient_trainer.py)", "function": "handle_exception", "line": 125}
